In [1]:
import numpy as np


In [9]:
b=np.eye(5,6,k=0,dtype=int)

In [10]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)[source]
#Return a 2-D array with ones on the diagonal and zeros elsewhere.

#Parameters:
#N:int
#Number of rows in the output.

#M:int, optional
#Number of columns in the output. If None, defaults to N.

#k:int, optional
#Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

#dtypedata-type, optional
#Data-type of the returned array.

In [11]:
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


In [12]:
for i in b:
    print(i, end=" ")

[1 0 0 0 0 0] [0 1 0 0 0 0] [0 0 1 0 0 0] [0 0 0 1 0 0] [0 0 0 0 1 0] 

In [13]:
for i in b:
    print(i)

[1 0 0 0 0 0]
[0 1 0 0 0 0]
[0 0 1 0 0 0]
[0 0 0 1 0 0]
[0 0 0 0 1 0]
