In [1]:
import numpy as np

In [2]:
li_2d = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]]

In [3]:
arr_2d = np.array(li_2d)

In [4]:
print(arr_2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [5]:
for i in arr_2d[2,0:3]:
    print(i,end=" ")

11 12 13 

In [6]:
for i in arr_2d[1:4,3]:
    print(i,end=" ")

9 14 19 

In [7]:
for i in arr_2d[2:4,:]:
    print(*i,end=" ")    

11 12 13 14 15 16 17 18 19 20 

In [8]:
for i in arr_2d[1:3,1:3]:
    print(*i,end=" ")   

7 8 12 13 

In [9]:
#Unpacking positional arguments
#When the arguments are in the form of sequences like list/tuple/range, 
#we can unpack them during the function call using the * operator. 
#An asterisk * is used for unpacking positional arguments during the function call.

In [12]:
#Range Syntax

#range(start, stop, step)

x = range(6)
for n in x:
  print(n)

0
1
2
3
4
5


In [18]:
for i in range(3):
    print(i)

0
1
2


In [19]:
##input_[2,0:3]
for i in range(3):
    print(arr_2d[2][i],end=" ")
print()

11 12 13 


In [20]:
##input_[1:4,3]
for i in range(1,4):
    print(arr_2d[i][3],end=" ")
print()

9 14 19 


In [21]:
##input_[2:4,:]
for i in range(2,4):
    for j in range(0,5):
        print(arr_2d[i][j],end=" ")
print()

11 12 13 14 15 16 17 18 19 20 


In [22]:
##input_[1:3,1:3]
for i in range(1,3):
    for j in range(1,3):
        print(arr_2d[i][j],end=" ")
print()

7 8 12 13 
