In [2]:
import numpy as np

In [3]:
arr = np.array([[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[ 6,5,4,3,2]])
sort_col=0
print(arr)

[[21 20 19 18 17]
 [16 15 14 13 12]
 [11 10  9  8  7]
 [ 6  5  4  3  2]]


In [14]:
print('first column')
print(arr[:,sort_col])

first column
[21 16 11  6]


In [15]:
# numpy.argsort() function is used to perform an indirect sort along the given axis using the algorithm specified by the kind keyword.

print('first column argsort result')
print(arr[:,sort_col].argsort())

first column argsort result
[3 2 1 0]


In [16]:
print('Sorted array')
print(arr[arr[:,sort_col].argsort()])

Sorted array
[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [13]:
print('first column sorted')
print(arr[arr[:,sort_col].argsort(),sort_col])

first column sorted
[ 6 11 16 21]
